@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttibuteIconSize 0

class InserirePassword{
-nomeAccount: String;
-password: String;
-percorso: Path;
+InserirePassword(nomeAccount: String, password: String, percorso: Path)
+inserire(tipo: int): void
}

class ControlloAccount{
-nomeAccount: String;
-percorso: Path;
-alfabetom: String[];
-alfabetoM: String[];
-numeri: String[];
-caratteriSpeciali: String[];
-spazio: String;
+ControlloAccount(nomeAccount: String, percorso: Path)
+controlloNome(tipo: int): int
+controlloPassword(password: int): int
+
}

class GeneratorePassword{
-password: StringBuilder;
-nomeAccount: String;
-percorso: Path;
-alfabetom: String[];
-alfabetoM: String[];
-caratteriSpeciali: String[];
+GeneratorePassword(nomeAccount: String, percorso: Path)
+generaPassword(tipo: int): void
}

@enduml